In [55]:
import numpy as np

predictions_estimator = np.load("/home/ubuntu/DeepLearningExamples_Anurag/TensorFlow2/Segmentation/MaskRCNN/scripts/predictions_estimator.npy", allow_pickle=True).item()
predictions_nonestimator = np.load("predictions_nonestimator.npy", allow_pickle=True).item()

In [26]:
predictions_estimator.keys()

dict_keys(['num_detections', 'detection_boxes', 'detection_classes', 'detection_scores', 'detection_masks', 'source_id', 'image_info'])

In [57]:
predictions_estimator['num_detections']

[array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=int32),
 array([100, 100, 100, 100, 100, 100, 100, 100], dtype=

In [33]:
print(len(predictions_estimator['detection_classes']))
print(predictions_estimator['detection_classes'][0].shape)

625
(8, 100)


In [12]:
for i, image_id in enumerate(predictions_estimator['source_id']):
    print(image_id)

[397133 565778 430961 473237 301135 458790  31269 355325]
[482917  61171 308430 141821 312278  21167 337498 218362]
[259571 560266 571313 116208 535578 504589 441286 519522]
[577182 253386 425702  57150 468124 218424  65736 176778]
[269196 332318 104669 486104 139099 201148 140270 320642]
[382122 201025 499109 325838  12062 319369   3553 346968]
[ 15272  79229 312720  47769  58393 455157  34257 359540]
[104803 217219 231822 195754  23666 151657 439290 549674]
[ 37777 297343  80671 228144 580294 460160 319721 100582]
[300659 314034  43314 410650  97679 148730 521405 213224]
[561679 486479 183127 340697 580757 464522 279541 144784]
[289222 222991  36844 363666 187144 473974   1000 104572]
[315450 186296 439994 514586 467511 231169 553990 322895]
[234807 448256 478136 527427 360325  26941 253819 229216]
[391375 188439 568981   1503 353180 486112 161799 427997]
[410878  61960  15597 315219   6213 495146 493442 344621]
[252219 336587 577539 206027 494869 458109 165351 555412]
[199977 291490

In [2]:
import numpy as np
predictions_all = np.load("predictions_all.npy", allow_pickle=True)

In [22]:
#         source_ids_all = gather_result_from_all_processes(source_ids)
#if MPI_rank() == 0:
all_predictions = []
source_ids = []
for i, p in enumerate(predictions_all):
    print(i)


0
1
2
3
4
5
6
7


In [5]:
predictions_results = dict()

for out in predictions_all:
    for k, v in out.items():
        if k not in predictions_results:
            predictions_results[k] = v
        else:
            predictions_results[k] += v

In [15]:
context = {}
context.update(predictions_all[0])
context.update(predictions_all[1])

In [59]:
context = predictions_all[0].copy()
#context['num_detections'].append(predictions_all[1]['num_detections'])

In [43]:
context['num_detections'].append([1,2,3,4])
len(predictions_all[0]['num_detections'])

78

In [53]:
test = np.array([100, 100, 100, 100, 100, 100, 100, 100])
context['num_detections'].append(predictions_all[1]['num_detections'])

In [60]:
context['num_detections'] += predictions_all[1]['num_detections']

In [69]:
print(len(predictions_results['detection_classes']))
print(predictions_results['detection_classes'][0].shape)

624
(8, 100)


In [8]:
from evaluation import gather_result_from_all_processes

import numpy as np
worker_predictions = np.load("predictions_all.npy", allow_pickle=True).item()

logging.info(worker_predictions['source_id'])
# DEBUG - print worker predictions
# _ = compute_coco_eval_metric_n(worker_predictions, False, validation_json_file)
coco = coco_metric.MaskCOCO()
_preds = copy.deepcopy(worker_predictions)
for k, v in _preds.items():
    # combined all results in flat structure for eval
    _preds[k] = np.concatenate(v, axis=0)
if MPI_rank() < 32:
    converted_predictions = coco.load_predictions(_preds, include_mask=True, is_image_mask=False)
    worker_source_ids = _preds['source_id']
else:
    converted_predictions = []
    worker_source_ids = []

# logging.info(converted_predictions)
# gather on rank 0
predictions_list = gather_result_from_all_processes(converted_predictions)

dict_keys(['num_detections', 'detection_boxes', 'detection_classes', 'detection_scores', 'class_outputs', 'box_outputs', 'anchor_boxes', 'detection_masks', 'source_id', 'image_info', 'images'])

In [30]:
import numpy as np
worker_prediction_0 = np.load("worker_source_id_0.npy", allow_pickle=True)
worker_prediction_1 = np.load("worker_source_id_1.npy", allow_pickle=True)
worker_prediction_2 = np.load("worker_source_id_2.npy", allow_pickle=True)
worker_prediction_3 = np.load("worker_source_id_3.npy", allow_pickle=True)
worker_prediction_4 = np.load("worker_source_id_4.npy", allow_pickle=True)
worker_prediction_5 = np.load("worker_source_id_5.npy", allow_pickle=True)
worker_prediction_6 = np.load("worker_source_id_6.npy", allow_pickle=True)
worker_prediction_7 = np.load("worker_source_id_7.npy", allow_pickle=True)

In [31]:
res = np.concatenate((worker_prediction_0, worker_prediction_1, worker_prediction_2, worker_prediction_3, worker_prediction_4, worker_prediction_5, worker_prediction_6, worker_prediction_7))

In [32]:
len(set(res))

4992

In [45]:
predictions_all = np.load("predictions_all_new_multi.npy", allow_pickle=True)
source_ids = np.load("source_ids_new_multi.npy", allow_pickle=True)

In [39]:
predictions_anurag = np.load("/home/ubuntu/DeepLearningExamples_Anurag/TensorFlow2/Segmentation/MaskRCNN/scripts/all_predictions_anurag.npy", allow_pickle=True)


In [46]:
len(predictions_all)

499200

In [44]:
predictions_anurag[0]

{'image_id': 397133,
 'bbox': [385.579345703125,
  67.13165283203125,
  111.04114532470703,
  281.49627685546875],
 'score': 0.96702653,
 'category_id': 1,
 'segmentation': {'size': [427, 640],
  'counts': b'QhS5;=4R78ULk0g3_OcKQ1Y4VO`Kn0]4XO^Ki0`4\\OZKh0d4\\OTKi0k41TJ7j56aI4\\6^301O1O00100O000O100O02N1O1O2N2F:E:K6L3M4K5L3O1M3M2O20O01O01UOaKjH`4S7n0O1O1O1O2O0O2O1O2N3L4M3M5K6J:F>B;E6J2N2N3M4L2N1O1O100O001O010O0001O1O1N4L3M3gLaK`Md4\\NlJk1MQNY1\\1U4_NjJn1d2kNd3P1UMSNU3h1Z4M2O1O1O1O1O2N2N3L2O2N2M3N2M3N2M3M5J8GXgl1'}}